Отправка на проверку.
AntonTyurin87/go_final_project pull request #1
Opened 2024-08-04 08:11 UTC by AntonTyurin87

2024-08-04 21:01 UTC, dirtymew requested changes
Привет Антон

теперь оформлено верно

хочется отметить:
- документацию
- make 
- логирование
- структуру проекта

дал рекомендации что поправить и улучшить, для первой итерации думаю достаточно

задания со звездочкой доделывать будешь?

2024-08-04 21:01 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
есть RUN go mod download  - это лишнее

2024-08-04 21:01 UTC, dirtymew commented on Dockerfile
> +COPY sqlite/scheduler_creator.sql ./bin/sqlite
а зачем он в контейнере?

2024-08-04 21:01 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.22
лучше туже версию что и в go.mod. использовать go 1.21.5

2024-08-04 21:01 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 TODO_DBFILE="" go build -o /app/bin/todorun ./cmd/todo/main.go
это CGO_ENABLED=0 GOOS=linux GOARCH=amd64 лучше в ENV

2024-08-04 21:01 UTC, dirtymew commented on Dockerfile
> +CMD ["/app/bin/todorun"]
мы же уже в WORKDIR - можно и относительным путем пользоваться

2024-08-04 21:01 UTC, dirtymew commented on cmd/todo/main.go
> +	"os"
что-то с ипортами по всему проекту - нужно попраиться

они должны быть сгруппированны и отсортированны

используй go imports, go fmt итд

2024-08-04 21:01 UTC, dirtymew commented on cmd/todo/main.go
> +	db, err := sqlite.InitDB(dbURL)
после завершения работы надо соединение закрыть

2024-08-04 21:01 UTC, dirtymew commented on cmd/todo/main.go
> +	fmt.Printf("Сервер TODO запущен! Порт %s.\n", port)
супер что добавил лог

2024-08-04 21:01 UTC, dirtymew commented on datawork/date_convert.go
> +		fmt.Println("реобразовать дату не удалось ", err)
мб логировать стоит на одном уровне - это рекомендация так как этой темы не было в курсе, требовать не буду

2024-08-04 21:01 UTC, dirtymew commented on datawork/next_date.go
> +		/*
лушние комментарии стоит убрать

2024-08-04 21:01 UTC, dirtymew commented on datawork/validation.go
> +func IDValidation(id string) (TaskData, error) {
мб это метод структуры task ?

2024-08-04 21:01 UTC, dirtymew commented on datawork/validation.go
> +type TaskData struct {
просто Task - и мб в файле task.go это сделать?

2024-08-04 21:01 UTC, dirtymew commented on datawork/validation.go
> +package datawork
название пакета не очень  мб сделать несколько

- date
      |- conv.go
      |- nextdate.go

- task
      |-task.go
      |-validate.go

2024-08-04 21:01 UTC, dirtymew commented on handlers/get_next_date.go
> +func GetNextDateHandler(w http.ResponseWriter, r *http.Request) {
лучше просто next_date.go

да и все хенжлеры сюда в пакет положить

2024-08-04 21:01 UTC, dirtymew commented on handlers/get_next_date.go
> +		w.Write([]byte(res))
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-08-04 21:01 UTC, dirtymew commented on cmd/todo/main.go
> +	r.Post("/api/task", storage.PostOneTaskHandler)
тут не очень хорошо сделано с точки зрения архитектуры

storage это слой которому стоит отвечать только за операции с бд
а handler это слой которому стоит отвечать только за работу по http
еще можно слой service добавить - который бы отвечал за операции с task

посмотри в практичекую работу про посылки там можно подсмотреть как это сделать

2024-08-04 21:01 UTC, dirtymew commented on sqlite/data_monipulation.go
> +package sqlite
название файла прям не очень sqlite/data_monipulation.go

2024-08-04 21:01 UTC, dirtymew commented on sqlite/data_monipulation.go
> +func (s *Storage) GetOneTaskHandler(w http.ResponseWriter, r *http.Request) {
уже выше писал - это не очень что сторадж хендлит http реквесты и респонсы

2024-08-04 21:01 UTC, dirtymew commented on sqlite/data_monipulation.go
> +					ORDER BY date LIMIT 20;`
лимит в константу стоит вынести

2024-08-04 21:01 UTC, dirtymew commented on sqlite/data_monipulation.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-08-06 16:41 UTC, AntonTyurin87 commented on Dockerfile
> +FROM golang:1.22
Принято

2024-08-06 16:52 UTC, AntonTyurin87 commented on Dockerfile
> +COPY sqlite/scheduler_creator.sql ./bin/sqlite
Если при запуске исполняемого бинарника по адресу из TODO_DBFILE не окажется БД или если эта БД не читается сервис должен создать БД сам. Так как исполняемый бинарник я укоадываю в папку bin, вместе с папкой web, то и исходник для создания БД туда же кладу.

2024-08-06 16:53 UTC, AntonTyurin87 commented on Dockerfile
> +RUN go mod tidy
Прнято. Удалил.

2024-08-06 17:03 UTC, AntonTyurin87 commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 TODO_DBFILE="" go build -o /app/bin/todorun ./cmd/todo/main.go
Принято. Исправил.

2024-08-06 17:07 UTC, AntonTyurin87 commented on Dockerfile
> +CMD ["/app/bin/todorun"]
Принято. Исправил.

2024-08-06 17:13 UTC, AntonTyurin87 commented on cmd/todo/main.go
> +	"os"
Запустил go fmt ./*. Даже в каждый каталог зашел. Вероятно моё IDE иначе видит структурирование импортов.  (Goland студенческая с дефолтными настройками).

2024-08-06 17:19 UTC, AntonTyurin87 commented on cmd/todo/main.go
> +	db, err := sqlite.InitDB(dbURL)
Принято. Исправил.

2024-08-06 17:23 UTC, AntonTyurin87 commented on datawork/date_convert.go
> +		fmt.Println("реобразовать дату не удалось ", err)
Оставлю сообщения как есть. Переделывать всю структуру сообщений сейчас сил нет. Когда буду доделывать проетк, так сказать не для "закрытия дедлайна", а себе в портфолио, тогда подумаю об уровнях логирования.

2024-08-06 17:28 UTC, AntonTyurin87 commented on datawork/next_date.go
> +		/*
Принято. Убрал.

2024-08-06 17:31 UTC, AntonTyurin87 commented on handlers/get_next_date.go
> +func GetNextDateHandler(w http.ResponseWriter, r *http.Request) {
Принято. Поправил.

2024-08-06 17:40 UTC, AntonTyurin87 commented on handlers/get_next_date.go
> +		w.Write([]byte(res))
Принято. Поправил.

2024-08-06 18:03 UTC, AntonTyurin87 commented on sqlite/data_monipulation.go
> +package sqlite
Принято. Изменил на storage_query.go.

2024-08-06 18:23 UTC, AntonTyurin87 commented on sqlite/data_monipulation.go
> +					ORDER BY date LIMIT 20;`
Принято. Вынес в константу.

2024-08-06 18:27 UTC, AntonTyurin87 commented on sqlite/data_monipulation.go
> +
Принято. Исправил.

2024-08-06 18:29 UTC, AntonTyurin87 commented on sqlite/data_monipulation.go
> +func (s *Storage) GetOneTaskHandler(w http.ResponseWriter, r *http.Request) {
Принято. Отделил работу с хранилищем в отдельный слой.

2024-08-06 18:40 UTC, AntonTyurin87 commented on cmd/todo/main.go
> +	r.Post("/api/task", storage.PostOneTaskHandler)
Разделил логику на три слоя. Обращение к БД прокидываю через переменную TodoStorage. Но мне кажется, что вызов в хендлере метода, который требует данную переменную не очень очевиден. Может как-то можно иначе (красивее) это сделать?

2024-08-06 20:21 UTC, AntonTyurin87 commented on datawork/validation.go
> +type TaskData struct {
Принято. Исправил.

2024-08-06 20:23 UTC, AntonTyurin87 commented on datawork/validation.go
> +func IDValidation(id string) (TaskData, error) {
Принято частично. Объединил в один файл task.go, но в качестве метода структуры представлять не стал.

2024-08-06 20:27 UTC, AntonTyurin87 commented on datawork/validation.go
> +package datawork
Принято частично. Из-за взаимных ссылок друг на друга в TaskDataValidation и NextDate (если дата меньше сегодняшней, то нужно присвоить NextDate) не получается красиво разделить по пакетам. Объединил в один пакет tasks. Но разделил на 4 файла.

2024-08-06 20:32 UTC, AntonTyurin87 commented
Добрый день.
Спасибо за подробные замечания в ревью.

Постарался максимально учесть.
Подробности в комментариях к замечаниям. 

Остальные задания со "звёздочкой" в рамках дедлайна по проекту выполнять не буду.

2024-08-07 13:00 UTC, dirtymew requested changes
Привет Антон

дал комментарии что еще поправить

2024-08-07 13:00 UTC, dirtymew commented on Dockerfile
> +ENV TODO_DBFILE=""
тут задублировалась TODO_DBFILE=""

2024-08-07 13:00 UTC, dirtymew commented on handlers/group_tasks.go
> +	"go_final_project/sqlite"
проблема с группировкой импортов

используй go imports и поправь во всем проекте

2024-08-07 13:00 UTC, dirtymew commented on sqlite/find_or_create_db.go
> +package sqlite
названия файла не очень sqlite/find_or_create_db.go

я бы рекомендовал тут назвать файл db.go и все функции дам собрать

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataRead(data tasks.Task) ([]byte, error) {
GetTask или Get

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +	if returnData.ID == "" {
лушняя проверке поле id должно быть всегда его бд контролирует

2024-08-07 13:00 UTC, dirtymew commented on sqlite/scheduler_creator.sql
> +  date VARCHAR(128) NOT NULL,
VARCHAR(8) хватит

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataWrite(data tasks.Task) ([]byte, error) {
AddTask или Create

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataUpdate(data tasks.Task) ([]byte, error) {
UpdateTask/Update

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +	if err != nil || num == 0 {
лучше 2 условия просто написать так будет лучше код выглядеть и гибче

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataDelete(data tasks.Task) ([]byte, error) {
Delete - ну думаю понятно что я имею ввиду

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataDone(data tasks.Task) ([]byte, error) {
это лучше сделать не в сторадж - так как это метод композиция других - если был слой service то это там стоило бы делать - а так в хендлере

но можно и оставить - это рекомендация

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +func (s *Storage) GroupTasksDataRead(search string) ([]byte, error) {
Find

2024-08-07 13:00 UTC, dirtymew commented on sqlite/storage_query.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-08-07 13:00 UTC, dirtymew commented on tasks/next_date.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
это лучше вынести в отдельный пакет про даты - это к задачам напрямую не относиться

2024-08-07 13:00 UTC, dirtymew commented on tasks/validation.go
> +		taskData.Date = fmt.Sprint(now.Format("20060102"))
20060102 - определи константу и везде ее используй

2024-08-07 15:24 UTC, AntonTyurin87 commented on tasks/validation.go
> +		taskData.Date = fmt.Sprint(now.Format("20060102"))
Принято. Поправил.

2024-08-07 15:56 UTC, AntonTyurin87 commented on tasks/validation.go
> +		taskData.Date = fmt.Sprint(now.Format("20060102"))
Принято. Ввёл константу.

2024-08-07 15:57 UTC, AntonTyurin87 commented on Dockerfile
> +ENV TODO_DBFILE=""
Принято. Поправил.

2024-08-07 16:10 UTC, AntonTyurin87 commented on handlers/group_tasks.go
> +	"go_final_project/sqlite"
У меня IDE автоматически всё форматирует. При сохранении форматирование приходит в соответствии с настройками. Разве что в настройках могу переключить на "goimports"
![Снимок экрана 2024-08-07 190826](https://github.com/user-attachments/assets/32a051ff-df91-40b5-90e2-ad188d7f1d58)

2024-08-07 16:12 UTC, AntonTyurin87 commented on handlers/group_tasks.go
> +	"go_final_project/sqlite"
Поправил в сооветствии с установками IDE.

2024-08-07 16:31 UTC, AntonTyurin87 commented on sqlite/find_or_create_db.go
> +package sqlite
Принято. Объединил функции из трёх файлов в один.

2024-08-07 16:32 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataRead(data tasks.Task) ([]byte, error) {
Принято. Поправил.

2024-08-07 16:34 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +	if returnData.ID == "" {
Принято. Поправил.

2024-08-07 16:35 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataWrite(data tasks.Task) ([]byte, error) {
Принято. Поправил.

2024-08-07 16:37 UTC, AntonTyurin87 commented on sqlite/scheduler_creator.sql
> +  date VARCHAR(128) NOT NULL,
Принято. Поправил.

2024-08-07 16:38 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataUpdate(data tasks.Task) ([]byte, error) {
Принято. Поправил.

2024-08-07 16:40 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +	if err != nil || num == 0 {
Принято. Поправил.

2024-08-07 16:41 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataDelete(data tasks.Task) ([]byte, error) {
ригято. Поправил.

2024-08-07 16:43 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +func (s *Storage) GroupTasksDataRead(search string) ([]byte, error) {
Принято. Поправил.

2024-08-07 16:48 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +
Принято. Поправил.

2024-08-07 16:50 UTC, AntonTyurin87 commented on sqlite/storage_query.go
> +func (s *Storage) OneTaskDataDone(data tasks.Task) ([]byte, error) {
Переименовал и оставил тут. Отдельный service пока не вижу смысла делать.

2024-08-07 16:59 UTC, AntonTyurin87 commented on tasks/next_date.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
При попытке вынести в отдельную папку возникает проблема с циклической ссылаемостью, которая в свою очередь обусловлена техническим заданием "Если дата задачи до/раньше сегодняшней, то надо вызвать NextDate и получить новую дату".
Оставлю так. Возможно нужно вводить отдельный слой валидации.
![1](https://github.com/user-attachments/assets/700770a8-f8cd-43af-b792-55d79ffead0d)
![2](https://github.com/user-attachments/assets/958a6f70-46f1-45dd-bfee-8cb1d5cc071b)

2024-08-07 18:33 UTC, AntonTyurin87 commented
Добрый вечер, Антон!

Принял практически все предложения и исправления, кроме перемещения "NextDate" в отдельный пакет. Причины отписал в комментариях к замечанию.

2024-08-08 14:55 UTC, dirtymew requested changes
Привет Антон

тесты падают - нужно понять почему и исправить

остальное в целом хорошо

2024-08-08 14:55 UTC, dirtymew commented on sqlite/db.go
> +		appPath, err := os.Executable()
лучше конечно чтоб по умолчанию в папке проекта бд создавалась

2024-08-08 14:55 UTC, dirtymew commented on handlers/one_task.go
> +func DeleteOneTaskHandler(w http.ResponseWriter, r *http.Request) {
<img width="793" alt="image" src="https://github.com/user-attachments/assets/b529bce2-6645-4c0a-8bf2-7472ca1dcb72">

@AntonTyurin87  падают тесты - нужно поправить

2024-08-08 14:55 UTC, dirtymew commented on tasks/next_date.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
достаточно просто вынес функции работы с датами - никаких циклов нет

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/870bf5b0-3eb6-4ab4-a5ec-addcf66ceb2c">

2024-08-10 05:36 UTC, AntonTyurin87 commented on sqlite/db.go
> +		appPath, err := os.Executable()
Принято. Исправил.

2024-08-10 05:49 UTC, AntonTyurin87 commented on handlers/one_task.go
> +func DeleteOneTaskHandler(w http.ResponseWriter, r *http.Request) {
Принято. Поправил. Ввёл в Makefile команду для очистки кэша тестов.

2024-08-10 06:10 UTC, AntonTyurin87 commented on tasks/next_date.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
Принято. Пересобрал код. Поменял названия нескольким переменным и функциям.

2024-08-10 06:24 UTC, AntonTyurin87 commented
Добрый день, Антон!
На этот раз, надеюсь, учел всё)

2024-08-10 12:28 UTC, dirtymew approved these changes
Привет Антон

все отлично 

задание считаю выполненным

Поздравляю и желаю удачи

2024-08-10 13:07 UTC, merged